version: '3.7'

services:
  node:
    build:
      dockerfile: 'Dockerfile'
      context: '.'
    working_dir: /home/node/app
    command: /bin/sh -c 'npm run dev'
    volumes:
      - ./:/home/node/app
    ports:
      - 5173:5173
